lira_marketplace_list:
  path: /listMarketPlace/list
  methods: [GET]
  defaults:
    _controller: Akki\SyliusPayumLyraMarketplacePlugin\Controller\LyraMarketPlaceApiTestController:listMarketPlace

km_sylius_payum_slimpay_notify:
  methods: [POST]
  path: /marketplace/notify
  defaults:
    _controller: Akki\SyliusPayumLyraMarketplacePlugin\Controller\NotifyController::doAction