imports:
    - { resource: 'services/state_machine.yaml' }
    - { resource: 'services/factory.yaml' }

services:
    akki.lyra_marketplace.form.type.gateway_configuration:
        class: Akki\SyliusPayumLyraMarketplacePlugin\Form\Type\LyraMarketplaceGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: lyra_marketplace, label: akki.lyra_marketplace.gateway_label }
            - { name: form.type }

    akki.lyra_marketplace.gateway_factory:
        class: Akki\SyliusPayumLyraMarketplacePlugin\Builder\LyraMarketplaceGatewayFactoryBuilder
        arguments:
            - 'Akki\SyliusPayumLyraMarketplacePlugin\Gateway\LyraMarketplaceGatewayFactory'
            - '@service_container'
        tags:
            - { name: payum.gateway_factory_builder, factory: lyra_marketplace }

    #notify
    Akki\SyliusPayumLyraMarketplacePlugin\Controller\NotifyController:
        public: true
        arguments:
            - '@service_container'
            - '@sylius.repository.payment_method'
            - '@sylius.repository.order'

    akki.lyra_marketplace.extension.update_payment_state:
        public: true
        class: Akki\SyliusPayumLyraMarketplacePlugin\Extension\UpdatePaymentStateExtension
        arguments:
            $factory: '@sm.factory'
        tags:
            - name: payum.extension
              factory: lyra_marketplace
              alias: flux_se.sylius_payum_stripe.extension.update_payment_state